language: node_js
sudo: false
node_js:
  - "4"
  - "5"
  - "6"
  - "7"
  - "8"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9
services:
  - couchdb
  - redis
env:
  - TRAVIS=travis CXX=g++-4.9
before_script:
  - curl -s -X PUT http://localhost:5984/_config/admins/shredder -d '"shredder"'
  - curl -X PUT http://shredder:shredder@localhost:5984/shredder